manifest:
  remotes:
    - name: zmkfirmware
      url-base: https://github.com/zmkfirmware
    - name: petejohanson
      url-base: https://github.com/petejohanson
    - name: RasmusKoit
      url-base: https://github.com/RasmusKoit
    - name: urob
      url-base: https://github.com/urob
    - name: filippor
      url-base: https://github.com/filippor
    # Additional modules containing boards/shields/custom code can be listed here as well
    # See https://docs.zephyrproject.org/3.2.0/develop/west/manifest.html#projects
  projects:
    - name: zmk
      remote: petejohanson
      revision: core/move-to-zephyr-4-1
      import: app/west.yml
    - name: zmk-keyboard-pipar
      remote: RasmusKoit
      revision: main
    - name: zmk-unicode
      remote: urob
      revision: v0.3
    - name: kb_zmk_ps2_mouse_trackpoint_driver
      remote: filippor
      revision: badjeff-4.1
  self:
    path: config