---
include:
  - board: pipar_point_left
    snippet: zmk-usb-logging
  - board: pipar_point_right
    snippet: studio-rpc-usb-uart zmk-usb-logging
  - board: pipar_point_right
    shield: settings_reset